*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW18AS39NJ00
* Property : L = 39[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 5MHz - 10GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW18AS39NJ00 port1 port2
C1 port1 port2 2.06e-14
L2 port1 1 4.35e-8
R2 1 port2 1.79e-1
R3 port1 port2 4.21e+4
L4 port1 2 8.43e-7
R4 2 port2 146
L5 port1 3 1.65e-6
R5 3 port2 835
L6 port1 4 2.80e-6
R6 4 port2 1.20e+4
L7 port1 5 4.39e-6
C7 5 6 1.93e-16
R7 6 port2 2.96e+3
L8 port1 7 2.68e-8
C8 7 8 8.18e-15
R8 8 port2 120
L9 port1 9 3.52e-9
C9 9 10 2.67e-14
R9 10 port2 11.0
.ENDS LQW18AS39NJ00
*----------------------------------------------------------------------
