*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* MURATA P/N : LQW2BAN68NG00
* Property : L = 68[nH]
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 50MHz - 20GHz
*   Temperature = 25 degC
*   DC Bias Current = 0 A
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT LQW2BAN68NG00 port1 port2
C1 port1 port2 7.36e-14
L2 port1 1 7.28e-8
R2 1 port2 1.60e-1
R3 port1 port2 4.85e+4
L4 port1 2 1.56e-6
R4 2 port2 53.4
L5 port1 3 2.27e-6
R5 3 port2 551
L6 port1 4 4.81e-6
R6 4 port2 1.02e+4
L7 port1 5 6.60e-7
C7 5 6 3.23e-15
R7 6 port2 301
L8 port1 7 5.75e-8
C8 7 8 1.21e-14
R8 8 port2 81.5
L9 port1 9 3.27e-8
C9 9 10 5.31e-15
R9 10 port2 119
L10 port1 11 1.63e-8
C10 11 12 4.75e-15
R10 12 port2 66.8
.ENDS LQW2BAN68NG00
*----------------------------------------------------------------------
